pipeline {
    agent any

    environment {
        SERVICE_DIR = 'api-gateway'
        IMAGE_NAME = 'khawlarouiss/api-gateway'
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        DOCKER_CREDENTIALS_ID = 'dockerlogin'
    }

    stages {

        stage('Compute Version') {
            when {
                changeset "${SERVICE_DIR}/**"
            }
            steps {
                script {
                    VERSION = sh(
                        script: "./scripts/version.sh ${IMAGE_NAME} ${BRANCH_NAME}",
                        returnStdout: true
                    ).trim()

                    echo "Computed version: ${VERSION}"
                }
            }
        }

        stage('Build Maven') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                }
            }
            tools {
                maven 'Maven 3.9.11'
                jdk 'jdk17'
            }
            steps {
                dir("${SERVICE_DIR}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    script {
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            docker.build("${IMAGE_NAME}:${VERSION}")
                        }
                    }
                }
            }
        }

        stage('Docker Push') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    script {
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            def img = docker.image("${IMAGE_NAME}:${VERSION}")
                            img.push()
                            img.push('latest')
                        }
                    }
                }
            }
        }

    }

    post {
        always {
            echo "Build finished with status: ${currentBuild.currentResult}"
            cleanWs()
        }
    }

}

