pipeline {
    agent any

    environment {
        SERVICE_DIR = 'api-gateway'
        IMAGE_NAME = 'khawlarouiss/api-gateway'
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        DOCKER_CREDENTIALS_ID = 'dockerlogin'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                }
            }
            tools {
                maven 'Maven 3.9.11'
                jdk 'jdk17'
            }
            steps {
                dir("${SERVICE_DIR}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    script {
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            docker.build("${IMAGE_NAME}:${BUILD_NUMBER}")
                        }
                    }
                }
            }
        }

        stage('Docker Push') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    script {
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            def img = docker.image("${IMAGE_NAME}:${BUILD_NUMBER}")
                            img.push()
                            img.push('latest')
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
