apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-service
  labels:
    app: authors-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authors-service
  template:
    metadata:
      labels:
        app: authors-service
    spec:
      containers:
        - name: authors-service
          image: khawlarouiss/authors-service:PLACEHOLDER
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: authors-service-config
