apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-service
  labels:
    app: authors-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors-service
  template:
    metadata:
      labels:
        app: authors-service
    spec:
      containers:
        - name: authors-service
          image: khawlarouiss/authors-service:PLACEHOLDER
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ENV 
          envFrom:
            - configMapRef:
                name: authors-service-config
