apiVersion: v1
kind: Service
metadata:
  name: authors-service
  labels:
    app: authors-service
spec:
  type: ClusterIP
  selector:
    app: authors-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
