# Prod namespace service URLs
authors.service.url=http://authors-service.prod.svc.cluster.local:80
books.service.url=http://books-service.prod.svc.cluster.local:80

# Gateway Routes for Prod
spring.cloud.gateway.routes[0].id=authors-route
spring.cloud.gateway.routes[0].uri=${authors.service.url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/authors/**

spring.cloud.gateway.routes[1].id=books-route
spring.cloud.gateway.routes[1].uri=${books.service.url}
spring.cloud.gateway.routes[1].predicates[0]=Path=/books/**