pipeline {
  
  agent any

  environment {
    SERVICE_DIR = 'authors-service'
    DOCKER_REGISTRY = 'https://index.docker.io/v1/'
    IMAGE_NAME  = 'khawlarouiss/authors-service'
    DOCKER_CREDENTIALS_ID = 'dockerlogin'
  }

  stages {

    stage('Build Maven') {
      when {
        changeset "authors-service/**"
      }
      tools {
        maven 'Maven 3.9.11'
        jdk 'jdk17'
      }
      steps {
        dir("${SERVICE_DIR}") {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Docker Build & Push') {
      when {
        changeset "authors-service/**"
      }
      steps {
        dir("${SERVICE_DIR}") {
          script {
            docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
              def img = docker.build("${IMAGE_NAME}:${BUILD_NUMBER}")
              img.push()
              img.push('latest')
            }
          }
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
