pipeline {
  
  agent any
  
  environment {
    SERVICE_DIR = 'authors-service'
    DOCKER_REGISTRY = 'https://index.docker.io/v1/'
    IMAGE_NAME = 'khawlarouiss/authors-service'
    DOCKER_CREDENTIALS_ID = 'dockerlogin'
  }
  
  stages {
    
    stage('Check for Changes') {
      steps {
        script {
          def changedFiles = sh(
            script: """
              if git rev-parse HEAD~1 >/dev/null 2>&1; then
                git diff --name-only HEAD~1 HEAD
              else
                git ls-files
              fi
            """,
            returnStdout: true
          ).trim()
          
          if (!changedFiles.contains("${SERVICE_DIR}/")) {
            currentBuild.result = 'NOT_BUILT'
            currentBuild.description = "⏭️ No changes in ${SERVICE_DIR}"
            error("Skipping - no changes in ${SERVICE_DIR}")
          }
          
          currentBuild.description = "🔨 Building ${SERVICE_DIR}"
        }
      }
    }
    
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    
    stage('Build Maven') {
      tools {
        maven 'Maven 3.9.11'
        jdk 'jdk17'
      }
      steps {
        dir("${SERVICE_DIR}") {
          sh 'mvn clean package -DskipTests'
        }
      }
    }
    
    stage('Docker Build & Push') {
      steps {
        dir("${SERVICE_DIR}") {
          script {
            docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
              def img = docker.build("${IMAGE_NAME}:${BUILD_NUMBER}")
              img.push()
              img.push('latest')
            }
          }
        }
      }
    }
  }
  
  post {
    always {
      cleanWs()
    }
  }
}
