apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-PLACEHOLDER   # Jenkins will append -dev or -prod
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: khawlarouiss/api-gateway:PLACEHOLDER
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: api-gateway-config
