pipeline {
    agent any

    environment {
        SERVICE_DIR = 'bookstore-frontend'
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        IMAGE_NAME  = 'khawlarouiss/bookstore-frontend'
        DOCKER_CREDENTIALS_ID = 'dockerlogin'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    
        stage('Build Angular') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                    expression { currentBuild.previousBuild == null }
              }
            }
            tools {
                nodejs 'Node 24'
            }
            steps {
                dir("${SERVICE_DIR}") {
                    sh 'npm ci'
                    sh 'npm run build -- --configuration production'
                }
            }
        }

        stage('Docker Build') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                    expression { currentBuild.previousBuild == null }
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    script {
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            docker.build("${IMAGE_NAME}:${BUILD_NUMBER}")
                        }
                    }
                }
            }
        }

        stage('Docker Push') {
            when {
                allOf {
                    branch 'main'
                    changeset "${SERVICE_DIR}/**"
                    expression { currentBuild.previousBuild == null }
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    script {
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            def img = docker.image("${IMAGE_NAME}:${BUILD_NUMBER}")
                            img.push()
                            img.push('latest')
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Build finished with status: ${currentBuild.currentResult}"
            cleanWs()
        }
    }

}

