pipeline {
    
    agent any

    environment {
        SERVICE_DIR = 'bookstore-frontend'
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        IMAGE_NAME  = 'khawlarouiss/bookstore-frontend'
        DOCKER_CREDENTIALS_ID = 'dockerlogin'
        KUBECONFIG_DEV = 'kubeconfig-dev'
        KUBECONFIG_PROD = 'kubeconfig-prod'
    }

    stages {

        stage('Compute Version') {
            when {
                changeset "${SERVICE_DIR}/**"
            }
            steps {
                script {
                    sh 'chmod +x scripts/version.sh'
                    env.VERSION = sh(
                        script: "./scripts/version.sh ${IMAGE_NAME} ${BRANCH_NAME}",
                        returnStdout: true
                    ).trim()
                    echo "Computed version: ${env.VERSION}"
                }
            }
        }
        
        stage('Build Angular') {
            when {
                changeset "${SERVICE_DIR}/**"
            }
            tools {
                nodejs 'Node 24'
            }
            steps {
                dir("${SERVICE_DIR}") {
                    sh 'npm ci'
                    script {
                        if (env.BRANCH_NAME == 'dev') {
                            sh 'npm run build -- --configuration development'
                        } else {
                            sh 'npm run build -- --configuration production'
                        }
                    }
                }
            }
        }

        stage('Docker Build') {
            when {
                changeset "${SERVICE_DIR}/**"
            }
            steps {
                script {
                    docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                        def buildConfig = (env.BRANCH_NAME == 'dev') ? 'development' : 'production'

                        docker.build(
                            "${IMAGE_NAME}:${env.VERSION}",
                            "--build-arg BUILD_CONFIG=${buildConfig} ${SERVICE_DIR}"
                        )
                    }
                }
            }
        }

        stage('Docker Push') {
            when {
                changeset "${SERVICE_DIR}/**"
            }
            steps {
                script {
                    docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                        def img = docker.image("${IMAGE_NAME}:${env.VERSION}")
                        img.push()
                        if (env.BRANCH_NAME == 'main') {
                            img.push('latest')
                        }
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            when {
                allOf {
                    changeset "${SERVICE_DIR}/**"
                    anyOf {
                        branch 'dev'
                        branch 'main'
                    }
                }
            }
            steps {
                script {
                    def namespace
                    def kubeCredId
                    def valuesFile
                    def environmentName
                    if (env.BRANCH_NAME == 'dev') {
                        namespace = 'dev'
                        kubeCredId = KUBECONFIG_DEV
                        valuesFile = "values-dev.yaml"
                        environmentName = "DEVELOPMENT"
                    } 
                    else if (env.BRANCH_NAME == 'main') {
                        namespace = 'prod'
                        kubeCredId = KUBECONFIG_PROD
                        valuesFile = "values-prod.yaml"
                        environmentName = "PRODUCTION"
                    }

                    input(
                        message: """
CONFIRM DEPLOYMENT

Service      : ${SERVICE_DIR}
Image Repo   : ${IMAGE_NAME}
Computed Tag : ${env.VERSION}
Branch       : ${env.BRANCH_NAME}
Environment  : ${environmentName}
Namespace    : ${namespace}

Do you want to proceed?
""",
                        ok: "Deploy"
                    )

                    withCredentials([file(credentialsId: kubeCredId, variable: 'KUBECONFIG')]) {
                        sh """
                        echo "Testing Kubernetes access..."
                        kubectl cluster-info
                        kubectl get nodes
                        """
                        
                        sh """
                        kubectl create namespace ${namespace} --dry-run=client -o yaml | kubectl apply -f -
                        """
                        
                        sh """
                        helm upgrade --install ${SERVICE_DIR} charts/microservice \
                        -f helm-values/${SERVICE_DIR}/${valuesFile} \
                        --set global.imageTag=${VERSION} \
                        --namespace ${namespace} \
                        --create-namespace
                        """

                        sh """
                        echo "Waiting for rollout..."

                        kubectl rollout status deployment/${SERVICE_DIR} -n ${namespace}
                        """

                        sh """
                        echo "Deployment resources:"

                        kubectl get pods -n ${namespace}
                        kubectl get svc -n ${namespace}
                        kubectl get ingress -n ${namespace}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished with status: ${currentBuild.currentResult}"
            cleanWs()
        }
    }
}


