apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-frontend
  namespace: ENV
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ENV.bookstore.com
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bookstore-frontend
                port:
                  number: 80